PS1="%m %~ 
>> "

export PATH=$HOME/opt/nvim/bin:$PATH
export PATH=$HOME/opt/ffmpeg/bin:$PATH
export PATH=$HOME/Library/Python/3.8/bin:$PATH

alias ls="ls -G"
alias la="ls -laG"
alias rel="source ~/.zshrc"
